### ISSUE TITLE
brew command not found

### ISSUE THREAD

**Issue by PengpeiZhu** [xiawenke/AstroSchedullerGo#2]
Brew command need for ./install.sh: line 31 is not on my computer so I have to install it manually, maybe consider adding this line in install.sh:  `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
which installs the brew command.

**Comment by xiawenke** [comment]
Got it. The `install.sh` is updated. Thanks!
